# Generated by Django 5.0.2 on 2024-02-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('air_pollution', models.FloatField()),
                ('alcohol_use', models.FloatField()),
                ('genetic_risk', models.FloatField()),
                ('chronic_lung_disease', models.FloatField()),
                ('Level', models.CharField(max_length=30)),
            ],
        ),
    ]
